-- CEP_F_End.sql

UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_WAR_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_SETTLEMENTS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_DANCE_AURORA_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]21 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_HUNT_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]30 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_DESERT_FOLKLORE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]31 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_TRANQUIL_REFUGE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]40 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_SEA_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]41 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SACRED_ISLES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]50 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ORAL_TRADITION_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]51 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SACRED_PATH_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]60 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ONE_WITH_NATURE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]61 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_STONE_CIRCLES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]62 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_TEARS_OF_GODS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]63 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FORMAL_LITURGY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]64 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_FESTIVALS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]65 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_OPEN_SKY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]70 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FERTILITY_RITES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]71 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ANCESTOR_WORSHIP_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]72 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MESSENGER_GODS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]73 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_CRAFTSMEN_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]74 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MONUMENT_GODS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]75 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SACRED_WATERS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:18:25:32]76 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_LOVE_SHORT';






UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_INTERFAITH_DIALOGUE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_HOLY_WARRIORS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]12 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PAPAL_PRIMACY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_INITIATION_RITES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]21 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CHURCH_PROPERTY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]22 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_TITHE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]23 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_WORLD_CHURCH_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]24 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PILGRIMAGE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]25 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CEREMONIAL_BURIAL_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]26 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PEACE_LOVING_SHORT';



UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FEED_THE_WORLD_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SWORDS_INTO_PLOWSHARES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]12 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_COMMUNITY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]13 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GURUSHIP_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_LITURGICAL_DRAMA_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]21 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MOSQUES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]22 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MONASTERIES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]23 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CHORAL_MUSIC_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]24 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_ART_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]25 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_DIVINE_INSPIRATION_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]26 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CATHEDRALS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]30 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ASCETICISM_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]31 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_CENTER_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]32 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PEACE_GARDENS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]33 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PAGODAS_SHORT';



UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_JUST_WAR_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FAITH_HEALERS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIQUARY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]30 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MESSIAH_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]31 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MISSIONARY_ZEAL_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]32 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_HOLY_ORDER_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]33 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ITINERANT_PREACHERS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]34 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_TEXTS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR:59:58:55]35 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_UNITY_SHORT';
