-- CEP_F_End.sql created by:
-- Beliefs tab of CEP_PoliciesTechsBeliefs.xls

UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_WAR_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_SETTLEMENTS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_DANCE_AURORA_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]21 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_HUNT_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]30 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_DESERT_FOLKLORE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]31 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_TRANQUIL_REFUGE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]40 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_SEA_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]41 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SACRED_ISLES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]50 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ORAL_TRADITION_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]51 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SACRED_PATH_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]60 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ONE_WITH_NATURE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]61 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_STONE_CIRCLES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]62 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_TEARS_OF_GODS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]63 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FORMAL_LITURGY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]64 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_FESTIVALS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]65 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_OPEN_SKY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]70 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FERTILITY_RITES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]71 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ANCESTOR_WORSHIP_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]72 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MESSENGER_GODS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]73 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GOD_CRAFTSMEN_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]74 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MONUMENT_GODS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]75 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SACRED_WATERS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]76 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_LOVE_SHORT';






UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_INTERFAITH_DIALOGUE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_HOLY_WARRIORS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]12 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PAPAL_PRIMACY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_INITIATION_RITES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]21 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CHURCH_PROPERTY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]22 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_TITHE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]23 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_WORLD_CHURCH_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]24 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PILGRIMAGE_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]25 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CEREMONIAL_BURIAL_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]26 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PEACE_LOVING_SHORT';



UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FEED_THE_WORLD_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_SWORDS_INTO_PLOWSHARES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]12 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_COMMUNITY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]13 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_GURUSHIP_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_LITURGICAL_DRAMA_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]21 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MOSQUES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]22 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MONASTERIES_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]23 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CHORAL_MUSIC_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]24 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_ART_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]25 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_DIVINE_INSPIRATION_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]26 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_CATHEDRALS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]30 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ASCETICISM_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]31 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_CENTER_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]32 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PEACE_GARDENS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]33 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_PAGODAS_SHORT';



UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]10 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_JUST_WAR_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]11 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_FAITH_HEALERS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]20 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIQUARY_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]30 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MESSIAH_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]31 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_MISSIONARY_ZEAL_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]32 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_HOLY_ORDER_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]33 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_ITINERANT_PREACHERS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]34 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_TEXTS_SHORT';
UPDATE Language_EN_US SET Text = '[COLOR_DARK_GREY]35 [ENDCOLOR]'||Text WHERE Tag = 'TXT_KEY_BELIEF_RELIGIOUS_UNITY_SHORT';
